### ISSUE TITLE
Typo in App Store Link

### ISSUE THREAD

**Issue by jakemcivor** [milador/VirtualJoystick#1]
In the Setup Guide, under the Usage section, there is a typo in the Link to the Android application on the Play Store

https://play.google.com/store/apps/details?id=com.milador.virtualjoysticko

Should be:
https://play.google.com/store/apps/details?id=com.milador.virtualjoystick

**Comment by milador** [comment]
@jakemcivor Fixed it. Thanks for finding the typo.
